# This is **NUMPY** notebook

Numpy Stands for numerical python and is the core python library for numeric and scientific computing

It consists of multi-dimensional array objects and a collection or routines for processing those arrays

# creating NumPy Array

In [1]:
# single- dimensional Array
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [2]:
# Multi- dimensional Array
import numpy as np
n1 = np.array([[10,20,30,40],[40,30,20,10]])
n1

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [1]:
import numpy as np
l1 = [1,2,3,4]
n1 = np.array(l1)
n1

array([1, 2, 3, 4])

In [2]:
type(n1)

numpy.ndarray